# ==============================
# APP
# ==============================
spring.application.name=messaging-service
server.port=8082

# ==============================
# PostgreSQL
# ==============================
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/groupchatdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:groupchat2024}

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=messaging
spring.jpa.show-sql=false

# ==============================
# RabbitMQ
# ==============================
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET:gruopChat-secret-key-2026-eafit-telematica-st0263}
jwt.expiration-ms=86400000

# ==============================
# LOGS
# ==============================
logging.level.eafit.gruopChat=DEBUG
logging.level.org.springframework.security=WARN


management.endpoints.web.exposure.include=health,mappings
management.endpoint.mappings.enabled=true
management.security.enabled=false